version: '3.4'

services:
  trish.api:
    image: ${DOCKER_REGISTRY-}trishapi
    build:
      context: .
      dockerfile: Trish.API/Dockerfile
    ports:
    - "8080:8080"
    - "8081:8081"

  python-service:
    build: 
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_START_RPC=true
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres:
    image: postgres:latest
    container_name: trish.db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=trishdb2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - ./.containers/trish-db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  cassandra_data:



 